[build]
  publish = "public"
  command = "gatsby build"
  functions = "functions"
[build.environment]
  NODE_VERSION = "14.3.0"
  YARN_VERSION = "1.22.4"
[template.environment]
  FAUNADB_SERVER_SECRET = "fnADfbdAsuACFD760u0R8bg0x12IkMDDik6Eekuz"
[[plugins]]
  package = "netlify-plugin-gatsby-cache"  
[[headers]]
  for = "/*"
[headers.values]
  Cache-Control = "public, max-age=31536000"
  Referrer-Policy = "strict-origin-when-cross-origin"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  Access-Control-Allow-Origin = "*"
  Vary = "Accept-Encoding"
  Set-Cookie = "HttpOnly; Secure; SameSite=Strict"
  Feature-Policy = "geolocation 'self' https://publiuslogic.com; autoplay 'none'; sync-xhr 'self' https://publiuslogic.com"
[[headers]]
for = "/static/*"
[headers.values]
    Cache-Control = "public, max-age=31536000"
[[redirects]]
  from = "/app/*"
  to = "/app.html"
  status = 200    